apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: currency-converter-rollout
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: currency-converter
        image: nishit7908/currency-converter:10999766339
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
  strategy:
    canary:
      steps:
      - setWeight: 20        # 20% traffic to new version; remainder goes to old version.
      - pause: {duration: 10s} # Pause to allow monitoring.
      - setWeight: 40        # Increase to 40% traffic.
      - pause: {duration: 10s}
      - setWeight: 60        # Increase to 60% traffic.
      - pause: {duration: 10s}
      - setWeight: 80        # Increase to 80% traffic.
      - pause: {duration: 10s}
