apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: currency-converter-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
        - name: currency-converter
          image: nishit7908/currency-converter:10999766339
          ports:
            - containerPort: 8080
